name: Run 3x-ui Install Script

on:
  workflow_dispatch:

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - name: Install 3x-ui
        run: |
          curl -Ls https://raw.githubusercontent.com/mhsanaei/3x-ui/master/install.sh -o install.sh
          echo "" | sudo bash install.sh
